version: '3.8'

services:
  rustdesk-api:
    image: kayung1012/kustdesk-api:latest  # 使用你的Docker Hub镜像
    container_name: rustdesk-api
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_LANG=zh-CN
      - RUSTDESK_API_RUSTDESK_ID_SERVER=192.168.1.66:21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=192.168.1.66:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://192.168.1.66:21114
      - RUSTDESK_API_RUSTDESK_KEY=your_rustdesk_key_here
      - RUSTDESK_API_APP_WEB_CLIENT=1
      - RUSTDESK_API_APP_REGISTER=false
      - RUSTDESK_API_APP_SHOW_SWAGGER=0
      - RUSTDESK_API_APP_MAX_CONCURRENT_DEVICES=3
    ports:
      - "21114:21114"
    volumes:
      - ./data/rustdesk/api:/app/data
      - ./conf:/app/conf
      - ./logs:/app/runtime
    restart: unless-stopped
    networks:
      - rustdesk-net

networks:
  rustdesk-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16